# Sample jobs — replace with real listings from BrighterMonday, ZoomTanzania, etc. later

JOBS = [
    {
        "id": "job001",
        "title": "Software Engineer",
        "company": "CRDB Bank",
        "location": "Dar es Salaam",
        "type": "Full-time",
        "salary": "TZS 2.5M – 4M / month",
        "posted": "2 days ago",
        "description": "Build and maintain banking applications serving millions of Tanzanians. Work with modern tech stack.",
        "requirements": [
            "3+ years experience in software development",
            "Strong in Python, Java, or JavaScript",
            "Experience with React, Node.js, or similar",
            "Knowledge of SQL and databases",
            "Bachelor's in Computer Science or related field",
        ],
        "keywords": [
            "python", "java", "javascript", "react", "node", "sql",
            "api", "rest", "git", "docker", "aws", "banking", "fintech",
        ],
        "apply_url": "https://www.crdbbank.co.tz/careers",
    },
    {
        "id": "job002",
        "title": "Data Analyst",
        "company": "Vodacom Tanzania",
        "location": "Dar es Salaam",
        "type": "Full-time",
        "salary": "TZS 2M – 3.5M / month",
        "posted": "1 week ago",
        "description": "Analyze customer and network data to drive business decisions across Tanzania.",
        "requirements": [
            "2+ years in data analysis",
            "Advanced SQL and Excel",
            "Experience with Python or R",
            "Knowledge of Power BI or Tableau",
            "Strong analytical thinking",
        ],
        "keywords": [
            "sql", "python", "excel", "power bi", "tableau", "r",
            "data", "analytics", "statistics", "visualization", "etl",
        ],
        "apply_url": "https://www.vodacom.co.tz/careers",
    },
    {
        "id": "job003",
        "title": "Junior Web Developer",
        "company": "ZoomTanzania",
        "location": "Dar es Salaam",
        "type": "Full-time",
        "salary": "TZS 1.2M – 2M / month",
        "posted": "3 days ago",
        "description": "Join our team building Tanzania's largest online classifieds platform.",
        "requirements": [
            "1+ years experience with web development",
            "Proficient in JavaScript, HTML, CSS",
            "Experience with React or Vue",
            "Familiar with Git and GitHub",
            "Portfolio of projects",
        ],
        "keywords": [
            "javascript", "html", "css", "react", "vue", "git",
            "web", "frontend", "api", "responsive",
        ],
        "apply_url": "https://www.zoomtanzania.com/careers",
    },
    {
        "id": "job004",
        "title": "AI/ML Engineer",
        "company": "NMB Bank",
        "location": "Dar es Salaam",
        "type": "Full-time",
        "salary": "TZS 3M – 5M / month",
        "posted": "5 days ago",
        "description": "Design and deploy machine learning models for fraud detection, credit scoring, and customer insights.",
        "requirements": [
            "3+ years in ML/AI engineering",
            "Strong Python skills",
            "Experience with TensorFlow or PyTorch",
            "Understanding of NLP or computer vision",
            "Master's degree preferred",
        ],
        "keywords": [
            "python", "machine learning", "ml", "ai", "tensorflow",
            "pytorch", "nlp", "deep learning", "pandas", "numpy",
            "scikit-learn", "docker", "aws", "fraud detection",
        ],
        "apply_url": "https://www.nmbbank.co.tz/careers",
    },
    {
        "id": "job005",
        "title": "Mobile Developer (Android)",
        "company": "Selcom",
        "location": "Dar es Salaam",
        "type": "Full-time",
        "salary": "TZS 2.5M – 4M / month",
        "posted": "1 week ago",
        "description": "Build mobile payment solutions used by thousands of businesses across East Africa.",
        "requirements": [
            "2+ years Android development",
            "Strong in Kotlin or Java",
            "Experience with REST APIs",
            "Knowledge of mobile security",
            "Published apps preferred",
        ],
        "keywords": [
            "android", "kotlin", "java", "mobile", "rest", "api",
            "firebase", "payment", "fintech", "git",
        ],
        "apply_url": "https://www.selcom.co.tz/careers",
    },
    {
        "id": "job006",
        "title": "Backend Developer",
        "company": "Tigo Tanzania",
        "location": "Dar es Salaam",
        "type": "Full-time",
        "salary": "TZS 2.5M – 4M / month",
        "posted": "4 days ago",
        "description": "Build scalable backend services for Tanzania's fastest growing telecom.",
        "requirements": [
            "3+ years backend experience",
            "Node.js, Python, or Java",
            "Experience with microservices",
            "Knowledge of PostgreSQL or MongoDB",
            "Familiar with cloud (AWS/GCP)",
        ],
        "keywords": [
            "backend", "node", "python", "java", "postgresql",
            "mongodb", "api", "microservices", "aws", "docker",
            "kubernetes", "rest",
        ],
        "apply_url": "https://www.tigo.co.tz/careers",
    },
    {
        "id": "job007",
        "title": "UI/UX Designer",
        "company": "Bongo Live",
        "location": "Dar es Salaam",
        "type": "Full-time",
        "salary": "TZS 1.5M – 3M / month",
        "posted": "6 days ago",
        "description": "Design user experiences for one of Tanzania's most innovative tech products.",
        "requirements": [
            "2+ years UI/UX design",
            "Proficient in Figma, Sketch",
            "Strong portfolio",
            "Understanding of user research",
            "Basic HTML/CSS",
        ],
        "keywords": [
            "figma", "sketch", "ui", "ux", "design", "prototyping",
            "user research", "html", "css", "wireframe", "adobe xd",
        ],
        "apply_url": "https://www.bongolive.co.tz/careers",
    },
    {
        "id": "job008",
        "title": "DevOps Engineer",
        "company": "Nala Payments",
        "location": "Dar es Salaam (Hybrid)",
        "type": "Full-time",
        "salary": "TZS 3M – 6M / month",
        "posted": "1 week ago",
        "description": "Manage cloud infrastructure and CI/CD for a fast-growing fintech startup.",
        "requirements": [
            "3+ years DevOps experience",
            "Strong AWS or GCP knowledge",
            "Experience with Docker, Kubernetes",
            "Familiar with Terraform",
            "Scripting (Python, Bash)",
        ],
        "keywords": [
            "docker", "kubernetes", "aws", "gcp", "terraform",
            "ci/cd", "jenkins", "gitlab", "python", "bash",
            "linux", "monitoring", "prometheus",
        ],
        "apply_url": "https://www.nala.com/careers",
    },
    {
        "id": "job009",
        "title": "Business Analyst",
        "company": "Deloitte Tanzania",
        "location": "Dar es Salaam",
        "type": "Full-time",
        "salary": "TZS 2M – 3.5M / month",
        "posted": "2 weeks ago",
        "description": "Work with clients across East Africa on transformation projects.",
        "requirements": [
            "2+ years business analysis",
            "Strong Excel and PowerPoint",
            "Experience with SQL",
            "Excellent communication",
            "Bachelor's in Business, Economics, or related",
        ],
        "keywords": [
            "business analysis", "sql", "excel", "powerpoint",
            "stakeholder", "requirements", "process", "agile",
            "scrum", "jira", "communication",
        ],
        "apply_url": "https://www2.deloitte.com/tz/en/careers.html",
    },
    {
        "id": "job010",
        "title": "Full Stack Developer",
        "company": "Tembo",
        "location": "Remote / Dar es Salaam",
        "type": "Full-time",
        "salary": "TZS 3M – 5M / month",
        "posted": "3 days ago",
        "description": "Build end-to-end features for a fast-growing social media platform.",
        "requirements": [
            "2+ years full stack experience",
            "React or Vue + Node.js",
            "Experience with MongoDB or PostgreSQL",
            "Understanding of REST/GraphQL",
            "Familiar with AWS",
        ],
        "keywords": [
            "react", "vue", "node", "javascript", "typescript",
            "mongodb", "postgresql", "graphql", "rest", "aws",
            "full stack", "git", "docker",
        ],
        "apply_url": "https://tembo.co.tz/careers",
    },
    {
        "id": "job011",
        "title": "Network Engineer",
        "company": "Airtel Tanzania",
        "location": "Dar es Salaam",
        "type": "Full-time",
        "salary": "TZS 2M – 3.5M / month",
        "posted": "1 week ago",
        "description": "Maintain and optimize network infrastructure across Tanzania.",
        "requirements": [
            "3+ years network engineering",
            "CCNA / CCNP certification",
            "Experience with routers, switches",
            "Knowledge of network security",
            "Good troubleshooting skills",
        ],
        "keywords": [
            "network", "ccna", "ccnp", "cisco", "routing",
            "switching", "firewall", "security", "tcp/ip", "linux",
        ],
        "apply_url": "https://www.airtel.co.tz/careers",
    },
    {
        "id": "job012",
        "title": "Product Manager",
        "company": "Jumia Tanzania",
        "location": "Dar es Salaam",
        "type": "Full-time",
        "salary": "TZS 3M – 5M / month",
        "posted": "5 days ago",
        "description": "Own product strategy and roadmap for Tanzania's leading e-commerce platform.",
        "requirements": [
            "3+ years product management",
            "Experience with agile/scrum",
            "Data-driven mindset",
            "Strong communication",
            "Bachelor's degree",
        ],
        "keywords": [
            "product", "roadmap", "agile", "scrum", "jira",
            "analytics", "user research", "stakeholder",
            "communication", "sql", "a/b testing",
        ],
        "apply_url": "https://group.jumia.com/careers",
    },
    {
        "id": "job013",
        "title": "Cyber Security Analyst",
        "company": "Stanbic Bank",
        "location": "Dar es Salaam",
        "type": "Full-time",
        "salary": "TZS 2.5M – 4.5M / month",
        "posted": "1 week ago",
        "description": "Protect banking systems from cyber threats and security incidents.",
        "requirements": [
            "2+ years cyber security experience",
            "Knowledge of SIEM tools",
            "Familiar with ISO 27001, NIST",
            "CISSP or CEH preferred",
            "Understanding of network security",
        ],
        "keywords": [
            "security", "cyber", "siem", "splunk", "iso 27001",
            "nist", "cissp", "ceh", "firewall", "linux", "python",
            "incident response", "penetration testing",
        ],
        "apply_url": "https://www.stanbicbank.co.tz/careers",
    },
    {
        "id": "job014",
        "title": "Junior Accountant",
        "company": "PwC Tanzania",
        "location": "Dar es Salaam",
        "type": "Full-time",
        "salary": "TZS 1.5M – 2.5M / month",
        "posted": "4 days ago",
        "description": "Assist with audit, tax, and advisory work for clients across industries.",
        "requirements": [
            "Bachelor's in Accounting or Finance",
            "CPA (T) part qualified",
            "Strong Excel skills",
            "Attention to detail",
            "0-2 years experience",
        ],
        "keywords": [
            "accounting", "finance", "excel", "cpa", "audit",
            "tax", "financial reporting", "ifrs", "quickbooks",
            "sap", "communication",
        ],
        "apply_url": "https://www.pwc.co.tz/careers",
    },
    {
        "id": "job015",
        "title": "Customer Support Specialist",
        "company": "M-Pesa Tanzania",
        "location": "Dar es Salaam",
        "type": "Full-time",
        "salary": "TZS 800K – 1.5M / month",
        "posted": "1 day ago",
        "description": "Provide excellent customer support for Tanzania's largest mobile money platform.",
        "requirements": [
            "1+ years customer service",
            "Excellent Swahili and English",
            "Comfortable with CRM systems",
            "Problem-solving skills",
            "Diploma or degree",
        ],
        "keywords": [
            "customer service", "support", "crm", "zendesk",
            "communication", "swahili", "english", "helpdesk",
            "problem solving", "ticketing",
        ],
        "apply_url": "https://www.vodacom.co.tz/careers",
    },
]
